import { computed, toValue } from 'vue';

const THEMES = {
    comercio: {
        colorName: 'purple',
        hex: '#9333ea',
        rgba: 'rgba(147, 51, 234, 0.1)',
        rgbaBilled: 'rgba(147, 51, 234, 0.75)',
        text: 'text-purple-600',
        textLight: 'text-purple-100',
        text400: 'text-purple-400',
        textMuted: 'text-purple-400',
        textDark: 'text-purple-950',
        textMedium: 'text-purple-700',
        textSoftAccent: 'text-purple-600 bg-purple-50',
        textSoft: 'text-purple-900',
        bg: 'bg-purple-600',
        bg500: 'bg-purple-500',
        bgDark: 'bg-purple-950',
        bgLight: 'bg-purple-600/10',
        bgLight2: 'bg-purple-600/10',
        bgSoftLight: 'bg-purple-600/5',
        bgSoft: 'bg-purple-50',
        badgeBg: 'bg-purple-100',
        gradient: 'from-purple-600 to-indigo-700',
        buttonText: 'text-purple-600',
        buttonBgHover: 'hover:bg-purple-50',
        bgSoftAccent: 'bg-purple-600 text-white shadow-lg shadow-purple-200',
        bgMuted: 'bg-purple-600/5',
        borderLight: 'border-purple-600/20',
        border: 'border-purple-600/20',
        borderMuted: 'border-purple-600/20',
        borderBottom: 'border-purple-600',
        borderBottomLight: 'border-b-purple-600/30',
        borderSoft: 'border-purple-100',
        borderHover: 'hover:border-purple-600/30',
        hoverBorder: 'hover:border-purple-600/20',
        hover: 'hover:bg-purple-500',
        hoverBg: 'hover:bg-purple-600',
        hoverText: 'hover:text-purple-600',
        groupHoverText: 'group-hover:text-purple-600',
        groupHoverBg: 'group-hover:bg-purple-600/5',
        groupHoverText500: 'group-hover:text-purple-500',
        shadow: 'shadow-purple-500/20',
        hoverShadow: 'hover:shadow-purple-500/10',
        shadowEmerald: 'shadow-purple-500/30',
        blurBg: 'bg-purple-500/10',
        bg200Opacity: 'bg-purple-500/20',
        text100: 'text-purple-100',
        text300: 'text-purple-300',
        focusRing: 'focus:ring-purple-600/10',
        focusRingForm: 'focus:ring-purple-600/20',
        focusRingInput: 'focus:ring-purple-600',
        focusBorder: 'focus:border-purple-600/30',
        focusBorderInput: 'focus:border-purple-600/50',
        focusText: 'group-focus-within:text-purple-600',
        checkboxText: 'text-purple-600 focus:ring-purple-600/20',
        activeMenuBg: 'bg-purple-50/50',
        hoverMenuBg: 'hover:bg-purple-50',
        logoBg: 'bg-purple-600 shadow-purple-900/50',
        tableHoverBg: 'hover:bg-purple-50/40',
        tableActiveBg: 'bg-purple-50/20',
        hoverBorderLight: 'hover:border-purple-500/20',
        tankCard: 'bg-purple-600 shadow-purple-900/10',
        tankZap: 'text-purple-500',
        progressbarBg: 'bg-purple-500',
        hoverBgLight: 'group-hover:bg-purple-50/30',
        hoverBg5: 'group-hover:bg-purple-50',
        shadowBg: 'shadow-purple-900/20',
        roomBg: 'bg-purple-950 shadow-purple-900/20',
        roomTextLight: 'text-purple-300',
        roomTextMuted: 'text-purple-200/60',
        roomBtn: 'text-purple-950 hover:bg-purple-600 hover:text-white shadow-purple-950/20'
    },
    oficina: {
        colorName: 'blue',
        hex: '#2563eb',
        rgba: 'rgba(37, 99, 235, 0.1)',
        rgbaBilled: 'rgba(37, 99, 235, 0.75)',
        text: 'text-blue-600',
        textLight: 'text-blue-100',
        text400: 'text-blue-400',
        textMuted: 'text-blue-400',
        textDark: 'text-blue-950',
        textMedium: 'text-blue-700',
        textSoftAccent: 'text-blue-600 bg-blue-50',
        textSoft: 'text-blue-900',
        bg: 'bg-blue-600',
        bg500: 'bg-blue-500',
        bgDark: 'bg-blue-950',
        bgLight: 'bg-blue-600/10',
        bgLight2: 'bg-blue-600/10',
        bgSoftLight: 'bg-blue-600/5',
        bgSoft: 'bg-blue-50',
        badgeBg: 'bg-blue-100',
        gradient: 'from-blue-600 to-indigo-700',
        buttonText: 'text-blue-600',
        buttonBgHover: 'hover:bg-blue-50',
        bgSoftAccent: 'bg-blue-600 text-white shadow-lg shadow-blue-200',
        bgMuted: 'bg-blue-600/5',
        borderLight: 'border-blue-600/20',
        border: 'border-blue-600/20',
        borderMuted: 'border-blue-600/20',
        borderBottom: 'border-blue-600',
        borderBottomLight: 'border-b-blue-600/30',
        borderSoft: 'border-blue-100',
        borderHover: 'hover:border-blue-600/30',
        hoverBorder: 'hover:border-blue-600/20',
        hover: 'hover:bg-blue-500',
        hoverBg: 'hover:bg-blue-600',
        hoverText: 'hover:text-blue-600',
        groupHoverText: 'group-hover:text-blue-600',
        groupHoverBg: 'group-hover:bg-blue-600/5',
        groupHoverText500: 'group-hover:text-blue-500',
        shadow: 'shadow-blue-500/20',
        hoverShadow: 'hover:shadow-blue-500/10',
        shadowEmerald: 'shadow-blue-500/30',
        blurBg: 'bg-blue-500/10',
        bg200Opacity: 'bg-blue-500/20',
        text100: 'text-blue-100',
        text300: 'text-blue-300',
        focusRing: 'focus:ring-blue-600/10',
        focusRingForm: 'focus:ring-blue-600/20',
        focusRingInput: 'focus:ring-blue-600',
        focusBorder: 'focus:border-blue-600/30',
        focusBorderInput: 'focus:border-blue-600/50',
        focusText: 'group-focus-within:text-blue-600',
        checkboxText: 'text-blue-600 focus:ring-blue-600/20',
        activeMenuBg: 'bg-blue-50/50',
        hoverMenuBg: 'hover:bg-blue-50',
        logoBg: 'bg-blue-600 shadow-blue-900/50',
        tableHoverBg: 'hover:bg-blue-50/40',
        tableActiveBg: 'bg-blue-50/20',
        hoverBorderLight: 'hover:border-blue-500/20',
        tankCard: 'bg-blue-600 shadow-blue-900/10',
        tankZap: 'text-blue-500',
        progressbarBg: 'bg-blue-500',
        hoverBgLight: 'group-hover:bg-blue-50/30',
        hoverBg5: 'group-hover:bg-blue-50',
        shadowBg: 'shadow-blue-900/20',
        roomBg: 'bg-blue-950 shadow-blue-900/20',
        roomTextLight: 'text-blue-300',
        roomTextMuted: 'text-blue-200/60',
        roomBtn: 'text-blue-950 hover:bg-blue-600 hover:text-white shadow-blue-950/20'
    },
    hogar: {
        colorName: 'emerald',
        hex: '#059669',
        rgba: 'rgba(5, 150, 105, 0.1)',
        rgbaBilled: 'rgba(5, 150, 105, 0.75)',
        text: 'text-emerald-600',
        textLight: 'text-emerald-100',
        text400: 'text-emerald-400',
        textMuted: 'text-emerald-400',
        textDark: 'text-emerald-900',
        textMedium: 'text-emerald-700',
        textSoftAccent: 'text-emerald-600 bg-emerald-50',
        textSoft: 'text-emerald-900',
        bg: 'bg-emerald-600',
        bg500: 'bg-emerald-500',
        bgDark: 'bg-emerald-950',
        bgLight: 'bg-emerald-600/10',
        bgLight2: 'bg-emerald-600/10',
        bgSoftLight: 'bg-emerald-600/5',
        bgSoft: 'bg-emerald-50',
        badgeBg: 'bg-emerald-100',
        gradient: 'from-emerald-600 to-teal-700',
        buttonText: 'text-emerald-600',
        buttonBgHover: 'hover:bg-emerald-50',
        bgSoftAccent: 'bg-emerald-600 text-white shadow-lg shadow-emerald-200',
        bgMuted: 'bg-emerald-600/5',
        borderLight: 'border-emerald-600/20',
        border: 'border-emerald-600/20',
        borderMuted: 'border-emerald-600/20',
        borderBottom: 'border-emerald-600',
        borderBottomLight: 'border-b-emerald-600/30',
        borderSoft: 'border-emerald-100',
        borderHover: 'hover:border-emerald-600/30',
        hoverBorder: 'hover:border-emerald-600/20',
        hover: 'hover:bg-emerald-500',
        hoverBg: 'hover:bg-emerald-600',
        hoverText: 'hover:text-emerald-600',
        groupHoverText: 'group-hover:text-emerald-600',
        groupHoverBg: 'group-hover:bg-emerald-600/5',
        groupHoverText500: 'group-hover:text-emerald-500',
        shadow: 'shadow-emerald-500/20',
        hoverShadow: 'hover:shadow-emerald-500/10',
        shadowEmerald: 'shadow-emerald-500/30',
        blurBg: 'bg-emerald-500/10',
        bg200Opacity: 'bg-emerald-500/20',
        text100: 'text-emerald-100',
        text300: 'text-emerald-300',
        focusRing: 'focus:ring-emerald-600/10',
        focusRingForm: 'focus:ring-emerald-600/20',
        focusRingInput: 'focus:ring-emerald-600',
        focusBorder: 'focus:border-emerald-600/30',
        focusBorderInput: 'focus:border-emerald-600/50',
        focusText: 'group-focus-within:text-emerald-600',
        checkboxText: 'text-emerald-600 focus:ring-emerald-600/20',
        activeMenuBg: 'bg-emerald-50/50',
        hoverMenuBg: 'hover:bg-emerald-50',
        logoBg: 'bg-emerald-600 shadow-emerald-900/50',
        tableHoverBg: 'hover:bg-emerald-50/40',
        tableActiveBg: 'bg-emerald-50/20',
        hoverBorderLight: 'hover:border-emerald-500/20',
        tankCard: 'bg-emerald-600 shadow-emerald-900/10',
        tankZap: 'text-emerald-500',
        progressbarBg: 'bg-emerald-500',
        hoverBgLight: 'group-hover:bg-emerald-50/30',
        hoverBg5: 'group-hover:bg-emerald-50',
        shadowBg: 'shadow-emerald-900/20',
        roomBg: 'bg-emerald-950 shadow-emerald-900/20',
        roomTextLight: 'text-emerald-300',
        roomTextMuted: 'text-emerald-200/60',
        roomBtn: 'text-emerald-950 hover:bg-emerald-600 hover:text-white shadow-emerald-950/20'
    }
};

export function getThemeTokens(type) {
    return THEMES[type] || THEMES.hogar;
}

export function useTheme(source) {
    const themeColors = computed(() => {
        const raw = toValue(source);
        const type = typeof raw === 'string' ? raw : (raw?.type || 'hogar');
        return getThemeTokens(type);
    });

    return {
        themeColors
    };
}
